// This file is auto-generated by @hey-api/openapi-ts

import {
  buildClientParams,
  type Client,
  type ClientMeta,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from './client';
import { client } from './client.gen';
import type {
  AddPetErrors,
  AddPetResponses,
  CreateUserErrors,
  CreateUserResponses,
  CreateUsersWithListInputErrors,
  CreateUsersWithListInputResponses,
  DeleteOrderErrors,
  DeleteOrderResponses,
  DeletePetErrors,
  DeletePetResponses,
  DeleteUserErrors,
  DeleteUserResponses,
  FindPetsByStatusErrors,
  FindPetsByStatusResponses,
  FindPetsByTagsErrors,
  FindPetsByTagsResponses,
  GetInventoryErrors,
  GetInventoryResponses,
  GetOrderByIdErrors,
  GetOrderByIdResponses,
  GetPetByIdErrors,
  GetPetByIdResponses,
  GetUserByNameErrors,
  GetUserByNameResponses,
  LoginUserErrors,
  LoginUserResponses,
  LogoutUserErrors,
  LogoutUserResponses,
  Order,
  Pet,
  PlaceOrderErrors,
  PlaceOrderResponses,
  UpdatePetErrors,
  UpdatePetResponses,
  UpdatePetWithFormErrors,
  UpdatePetWithFormResponses,
  UpdateUserErrors,
  UpdateUserResponses,
  UploadFileErrors,
  UploadFileResponses,
  User,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
  protected client: Client;

  constructor(args?: { client?: Client }) {
    this.client = args?.client ?? client;
  }
}

class HeyApiRegistry<T> {
  private readonly defaultKey = 'default';

  private readonly instances: Map<string, T> = new Map();

  get(key?: string): T {
    const instance = this.instances.get(key ?? this.defaultKey);
    if (!instance) {
      throw new Error(`No SDK client found. Create one with "new Sdk()" to fix this error.`);
    }
    return instance;
  }

  set(value: T, key?: string): void {
    this.instances.set(key ?? this.defaultKey, value);
  }
}

export class Sdk extends HeyApiClient {
  public static readonly __registry: HeyApiRegistry<Sdk> = new HeyApiRegistry<Sdk>();

  constructor(args?: { client?: Client; key?: string }) {
    super(args);
    Sdk.__registry.set(this, args?.key);
  }

  /**
   * Add a new pet to the store.
   *
   * Add a new pet to the store.
   */
  public addPet<ThrowOnError extends boolean = false>(
    parameters: {
      pet: Pet;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<AddPetResponses, AddPetErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ key: 'pet', map: 'body' }] }]);
    return (options?.client ?? this.client).post<AddPetResponses, AddPetErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Update an existing pet.
   *
   * Update an existing pet by Id.
   */
  public updatePet<ThrowOnError extends boolean = false>(
    parameters: {
      pet: Pet;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<UpdatePetResponses, UpdatePetErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ key: 'pet', map: 'body' }] }]);
    return (options?.client ?? this.client).put<UpdatePetResponses, UpdatePetErrors, ThrowOnError>({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Finds Pets by status.
   *
   * Multiple status values can be provided with comma separated strings.
   */
  public findPetsByStatus<ThrowOnError extends boolean = false>(
    parameters: {
      status: 'available' | 'pending' | 'sold';
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<FindPetsByStatusResponses, FindPetsByStatusErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'query', key: 'status' }] }]);
    return (options?.client ?? this.client).get<
      FindPetsByStatusResponses,
      FindPetsByStatusErrors,
      ThrowOnError
    >({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet/findByStatus',
      ...options,
      ...params,
    });
  }

  /**
   * Finds Pets by tags.
   *
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   */
  public findPetsByTags<ThrowOnError extends boolean = false>(
    parameters: {
      tags: Array<string>;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<FindPetsByTagsResponses, FindPetsByTagsErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'query', key: 'tags' }] }]);
    return (options?.client ?? this.client).get<
      FindPetsByTagsResponses,
      FindPetsByTagsErrors,
      ThrowOnError
    >({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet/findByTags',
      ...options,
      ...params,
    });
  }

  /**
   * Deletes a pet.
   *
   * Delete a pet.
   */
  public deletePet<ThrowOnError extends boolean = false>(
    parameters: {
      api_key?: string;
      petId: number;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeletePetResponses, DeletePetErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: 'headers', key: 'api_key' },
            { in: 'path', key: 'petId' },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).delete<
      DeletePetResponses,
      DeletePetErrors,
      ThrowOnError
    >({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet/{petId}',
      ...options,
      ...params,
    });
  }

  /**
   * Find pet by ID.
   *
   * Returns a single pet.
   */
  public getPetById<ThrowOnError extends boolean = false>(
    parameters: {
      petId: number;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetPetByIdResponses, GetPetByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'petId' }] }]);
    return (options?.client ?? this.client).get<
      GetPetByIdResponses,
      GetPetByIdErrors,
      ThrowOnError
    >({
      security: [
        { name: 'api_key', type: 'apiKey' },
        { scheme: 'bearer', type: 'http' },
      ],
      url: '/pet/{petId}',
      ...options,
      ...params,
    });
  }

  /**
   * Updates a pet in the store with form data.
   *
   * Updates a pet resource based on the form data.
   */
  public updatePetWithForm<ThrowOnError extends boolean = false>(
    parameters: {
      petId: number;
      name?: string;
      status?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<UpdatePetWithFormResponses, UpdatePetWithFormErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: 'path', key: 'petId' },
            { in: 'query', key: 'name' },
            { in: 'query', key: 'status' },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      UpdatePetWithFormResponses,
      UpdatePetWithFormErrors,
      ThrowOnError
    >({
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet/{petId}',
      ...options,
      ...params,
    });
  }

  /**
   * Uploads an image.
   *
   * Upload image of the pet.
   */
  public uploadFile<ThrowOnError extends boolean = false>(
    parameters: {
      petId: number;
      additionalMetadata?: string;
      body?: Blob | File;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<UploadFileResponses, UploadFileErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: 'path', key: 'petId' },
            { in: 'query', key: 'additionalMetadata' },
            { key: 'body', map: 'body' },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).post<
      UploadFileResponses,
      UploadFileErrors,
      ThrowOnError
    >({
      bodySerializer: null,
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/pet/{petId}/uploadImage',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/octet-stream',
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Returns pet inventories by status.
   *
   * Returns a map of status codes to quantities.
   */
  public getInventory<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetInventoryResponses, GetInventoryErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<
      GetInventoryResponses,
      GetInventoryErrors,
      ThrowOnError
    >({
      security: [{ name: 'api_key', type: 'apiKey' }],
      url: '/store/inventory',
      ...options,
    });
  }

  /**
   * Place an order for a pet.
   *
   * Place a new order in the store.
   */
  public placeOrder<ThrowOnError extends boolean = false>(
    parameters?: {
      order?: Order;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<PlaceOrderResponses, PlaceOrderErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ key: 'order', map: 'body' }] }]);
    return (options?.client ?? this.client).post<
      PlaceOrderResponses,
      PlaceOrderErrors,
      ThrowOnError
    >({
      url: '/store/order',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Delete purchase order by identifier.
   *
   * For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.
   */
  public deleteOrder<ThrowOnError extends boolean = false>(
    parameters: {
      orderId: number;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteOrderResponses, DeleteOrderErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'orderId' }] }]);
    return (options?.client ?? this.client).delete<
      DeleteOrderResponses,
      DeleteOrderErrors,
      ThrowOnError
    >({
      url: '/store/order/{orderId}',
      ...options,
      ...params,
    });
  }

  /**
   * Find purchase order by ID.
   *
   * For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
   */
  public getOrderById<ThrowOnError extends boolean = false>(
    parameters: {
      orderId: number;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetOrderByIdResponses, GetOrderByIdErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'orderId' }] }]);
    return (options?.client ?? this.client).get<
      GetOrderByIdResponses,
      GetOrderByIdErrors,
      ThrowOnError
    >({
      url: '/store/order/{orderId}',
      ...options,
      ...params,
    });
  }

  /**
   * Create user.
   *
   * This can only be done by the logged in user.
   */
  public createUser<ThrowOnError extends boolean = false>(
    parameters?: {
      user?: User;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<CreateUserResponses, CreateUserErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ key: 'user', map: 'body' }] }]);
    return (options?.client ?? this.client).post<
      CreateUserResponses,
      CreateUserErrors,
      ThrowOnError
    >({
      url: '/user',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Creates list of users with given input array.
   *
   * Creates list of users with given input array.
   */
  public createUsersWithListInput<ThrowOnError extends boolean = false>(
    parameters?: {
      body?: Array<User>;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<
    CreateUsersWithListInputResponses,
    CreateUsersWithListInputErrors,
    ThrowOnError
  > {
    const params = buildClientParams([parameters], [{ args: [{ key: 'body', map: 'body' }] }]);
    return (options?.client ?? this.client).post<
      CreateUsersWithListInputResponses,
      CreateUsersWithListInputErrors,
      ThrowOnError
    >({
      url: '/user/createWithList',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
        ...params.headers,
      },
    });
  }

  /**
   * Logs user into the system.
   *
   * Log into the system.
   */
  public loginUser<ThrowOnError extends boolean = false>(
    parameters?: {
      username?: string;
      password?: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<LoginUserResponses, LoginUserErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: 'query', key: 'username' },
            { in: 'query', key: 'password' },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).get<LoginUserResponses, LoginUserErrors, ThrowOnError>({
      url: '/user/login',
      ...options,
      ...params,
    });
  }

  /**
   * Logs out current logged in user session.
   *
   * Log user out of the system.
   */
  public logoutUser<ThrowOnError extends boolean = false>(
    options?: Options<never, ThrowOnError>,
  ): RequestResult<LogoutUserResponses, LogoutUserErrors, ThrowOnError> {
    return (options?.client ?? this.client).get<
      LogoutUserResponses,
      LogoutUserErrors,
      ThrowOnError
    >({ url: '/user/logout', ...options });
  }

  /**
   * Delete user resource.
   *
   * This can only be done by the logged in user.
   */
  public deleteUser<ThrowOnError extends boolean = false>(
    parameters: {
      username: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<DeleteUserResponses, DeleteUserErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'username' }] }]);
    return (options?.client ?? this.client).delete<
      DeleteUserResponses,
      DeleteUserErrors,
      ThrowOnError
    >({
      url: '/user/{username}',
      ...options,
      ...params,
    });
  }

  /**
   * Get user by user name.
   *
   * Get user detail based on username.
   */
  public getUserByName<ThrowOnError extends boolean = false>(
    parameters: {
      username: string;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<GetUserByNameResponses, GetUserByNameErrors, ThrowOnError> {
    const params = buildClientParams([parameters], [{ args: [{ in: 'path', key: 'username' }] }]);
    return (options?.client ?? this.client).get<
      GetUserByNameResponses,
      GetUserByNameErrors,
      ThrowOnError
    >({
      url: '/user/{username}',
      ...options,
      ...params,
    });
  }

  /**
   * Update user resource.
   *
   * This can only be done by the logged in user.
   */
  public updateUser<ThrowOnError extends boolean = false>(
    parameters: {
      username: string;
      user?: User;
    },
    options?: Options<never, ThrowOnError>,
  ): RequestResult<UpdateUserResponses, UpdateUserErrors, ThrowOnError> {
    const params = buildClientParams(
      [parameters],
      [
        {
          args: [
            { in: 'path', key: 'username' },
            { key: 'user', map: 'body' },
          ],
        },
      ],
    );
    return (options?.client ?? this.client).put<
      UpdateUserResponses,
      UpdateUserErrors,
      ThrowOnError
    >({
      url: '/user/{username}',
      ...options,
      ...params,
      headers: {
        'Content-Type': 'application/json',
        ...options?.headers,
        ...params.headers,
      },
    });
  }
}
